import type { Metadata } from "next";
import "../../app/globals.css";

import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Prueba hiBeauty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <Toaster position="top-center" richColors />
    </>
  );
}
